### ISSUE TITLE
Issue with mmcv version

### ISSUE THREAD

**Issue by jerry3chen** [SamsungLabs/td3d#10]
Hi,
when I preprocess S3dis data with file "tools/create_data.py", I run into problem:
File "tools/create_data.py", line 5, in <module>
    from tools.data_converter import indoor_converter as indoor
ModuleNotFoundError: No module named 'tools.data_converter'

so I run with command "python -m tools.create_data.py s3dis ***", but I run into weird mmcv version problem:
If I run with version 1.6.0, i get:
Traceback (most recent call last):
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/jerry/3D/3d_seg/td3d/td3d/tools/create_data.py", line 6, in <module>
    from tools.data_converter import kitti_converter as kitti
  File "/home/jerry/3D/3d_seg/td3d/td3d/tools/data_converter/kitti_converter.py", line 9, in <module>
    from mmdet3d.core.bbox import box_np_ops, points_cam2img
  File "/home/jerry/3D/3d_seg/td3d/td3d/mmdet3d/__init__.py", line 4, in <module>
    import mmdet
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/__init__.py", line 16, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.6.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

But if I change the version to 2.0.0, I get this error instead:
Traceback (most recent call last):
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/jerry/3D/3d_seg/td3d/td3d/tools/create_data.py", line 6, in <module>
    from tools.data_converter import kitti_converter as kitti
  File "/home/jerry/3D/3d_seg/td3d/td3d/tools/data_converter/kitti_converter.py", line 9, in <module>
    from mmdet3d.core.bbox import box_np_ops, points_cam2img
  File "/home/jerry/3D/3d_seg/td3d/td3d/mmdet3d/__init__.py", line 26, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.4.8, <=1.6.0.

It seems that the newest openmmlab does not agree with this code.
How can we fix this?

Thanks

**Comment by filaPro** [comment]
Hi @jerry3chen ,

Can you please follow library versions from our [Dockerfile](https://github.com/SamsungLabs/td3d/blob/main/docker/Dockerfile), including `mmcv-full==1.6.0` and `mmdet==2.24.1`?

**Comment by jerry3chen** [comment]
Hi @filaPro ,

If I only manually change the version of mmcv-full and mmdet, I get the same version error.

Then I tried a fresh environment with configs in the docker file, I get the following error when running` pip install -U git+https://github.com/NVIDIA/MinkowskiEngine@405b39cb7e68c2ec1b4ac8c4b4ca9fa6fcfcb2fc -v --no-deps     --install-option="--blas=openblas"     --install-option="--force_cuda"`:

```
Using pip 23.0.1 from /home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/pip (python 3.9)
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option / --install-option. Consider using --config-settings for more flexibility.
DEPRECATION: --install-option is deprecated because it forces pip to use the 'setup.py install' command which is itself deprecated. pip 23.1 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11358
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Collecting git+https://github.com/NVIDIA/MinkowskiEngine@405b39cb7e68c2ec1b4ac8c4b4ca9fa6fcfcb2fc
  Cloning https://github.com/NVIDIA/MinkowskiEngine (to revision 405b39cb7e68c2ec1b4ac8c4b4ca9fa6fcfcb2fc) to /tmp/pip-req-build-evizr7he
  Running command git version
  git version 2.34.1
  Running command git clone --filter=blob:none https://github.com/NVIDIA/MinkowskiEngine /tmp/pip-req-build-evizr7he
  Cloning into '/tmp/pip-req-build-evizr7he'...
  Updating files:   0% (2/244)
  Updating files:   1% (3/244)
  Updating files:   2% (5/244)
  Updating files:   3% (8/244)
  Updating files:   4% (10/244)
  Updating files:   5% (13/244)
  Updating files:   6% (15/244)
  Updating files:   7% (18/244)
  Updating files:   8% (20/244)
  Updating files:   9% (22/244)
  Updating files:  10% (25/244)
  Updating files:  11% (27/244)
  Updating files:  12% (30/244)
  Updating files:  13% (32/244)
  Updating files:  14% (35/244)
  Updating files:  15% (37/244)
  Updating files:  16% (40/244)
  Updating files:  17% (42/244)
  Updating files:  18% (44/244)
  Updating files:  19% (47/244)
  Updating files:  20% (49/244)
  Updating files:  21% (52/244)
  Updating files:  22% (54/244)
  Updating files:  23% (57/244)
  Updating files:  24% (59/244)
  Updating files:  25% (61/244)
  Updating files:  26% (64/244)
  Updating files:  27% (66/244)
  Updating files:  28% (69/244)
  Updating files:  29% (71/244)
  Updating files:  30% (74/244)
  Updating files:  31% (76/244)
  Updating files:  32% (79/244)
  Updating files:  33% (81/244)
  Updating files:  34% (83/244)
  Updating files:  35% (86/244)
  Updating files:  36% (88/244)
  Updating files:  37% (91/244)
  Updating files:  38% (93/244)
  Updating files:  39% (96/244)
  Updating files:  40% (98/244)
  Updating files:  41% (101/244)
  Updating files:  42% (103/244)
  Updating files:  43% (105/244)
  Updating files:  44% (108/244)
  Updating files:  45% (110/244)
  Updating files:  46% (113/244)
  Updating files:  47% (115/244)
  Updating files:  48% (118/244)
  Updating files:  49% (120/244)
  Updating files:  50% (122/244)
  Updating files:  51% (125/244)
  Updating files:  52% (127/244)
  Updating files:  53% (130/244)
  Updating files:  54% (132/244)
  Updating files:  55% (135/244)
  Updating files:  56% (137/244)
  Updating files:  57% (140/244)
  Updating files:  58% (142/244)
  Updating files:  59% (144/244)
  Updating files:  60% (147/244)
  Updating files:  61% (149/244)
  Updating files:  62% (152/244)
  Updating files:  63% (154/244)
  Updating files:  64% (157/244)
  Updating files:  65% (159/244)
  Updating files:  66% (162/244)
  Updating files:  67% (164/244)
  Updating files:  68% (166/244)
  Updating files:  69% (169/244)
  Updating files:  70% (171/244)
  Updating files:  71% (174/244)
  Updating files:  72% (176/244)
  Updating files:  73% (179/244)
  Updating files:  74% (181/244)
  Updating files:  75% (183/244)
  Updating files:  76% (186/244)
  Updating files:  77% (188/244)
  Updating files:  78% (191/244)
  Updating files:  79% (193/244)
  Updating files:  80% (196/244)
  Updating files:  81% (198/244)
  Updating files:  82% (201/244)
  Updating files:  83% (203/244)
  Updating files:  84% (205/244)
  Updating files:  85% (208/244)
  Updating files:  86% (210/244)
  Updating files:  87% (213/244)
  Updating files:  88% (215/244)
  Updating files:  89% (218/244)
  Updating files:  90% (220/244)
  Updating files:  91% (223/244)
  Updating files:  92% (225/244)
  Updating files:  93% (227/244)
  Updating files:  94% (230/244)
  Updating files:  95% (232/244)
  Updating files:  96% (235/244)
  Updating files:  97% (237/244)
  Updating files:  98% (240/244)
  Updating files:  99% (242/244)
  Updating files: 100% (244/244)
  Updating files: 100% (244/244), done.
  Running command git show-ref 405b39cb7e68c2ec1b4ac8c4b4ca9fa6fcfcb2fc
  Running command git rev-parse -q --verify 'sha^405b39cb7e68c2ec1b4ac8c4b4ca9fa6fcfcb2fc'
  Running command git fetch -q https://github.com/NVIDIA/MinkowskiEngine 405b39cb7e68c2ec1b4ac8c4b4ca9fa6fcfcb2fc
  Running command git rev-parse FETCH_HEAD
  405b39cb7e68c2ec1b4ac8c4b4ca9fa6fcfcb2fc
  Running command git rev-parse HEAD
  02fc608bea4c0549b0a7b00ca1bf15dee4a0b228
  Running command git checkout -q 405b39cb7e68c2ec1b4ac8c4b4ca9fa6fcfcb2fc
  Resolved https://github.com/NVIDIA/MinkowskiEngine to commit 405b39cb7e68c2ec1b4ac8c4b4ca9fa6fcfcb2fc
  Running command git rev-parse HEAD
  405b39cb7e68c2ec1b4ac8c4b4ca9fa6fcfcb2fc
  Running command python setup.py egg_info
  WARNING: Skipping MinkowskiEngine as it is not installed.
  /tmp/pip-req-build-evizr7he/setup.py:129: UserWarning: torch.cuda.is_available() is False. MinkowskiEngine will compile with CPU_ONLY. Please use `--force_cuda` to compile with CUDA.
    warnings.warn(
  /tmp/pip-req-build-evizr7he/setup.py:201: DeprecationWarning:

    `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
    of the deprecation of `distutils` itself. It will be removed for
    Python >= 3.12. For older Python versions it will remain present.
    It is recommended to use `setuptools < 60.0` for those Python versions.
    For more details, see:
      https://numpy.org/devdocs/reference/distutils_status_migration.html


    import numpy.distutils.system_info as sysinfo
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.7'
  --------------------------------
  | WARNING: CPU_ONLY build set  |
  --------------------------------

  Using BLAS=openblas
  Using the default compiler
  running egg_info
  creating /tmp/pip-pip-egg-info-6so_dhlf/MinkowskiEngine.egg-info
  writing /tmp/pip-pip-egg-info-6so_dhlf/MinkowskiEngine.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-6so_dhlf/MinkowskiEngine.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-6so_dhlf/MinkowskiEngine.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-6so_dhlf/MinkowskiEngine.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-6so_dhlf/MinkowskiEngine.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-6so_dhlf/MinkowskiEngine.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-6so_dhlf/MinkowskiEngine.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Installing collected packages: MinkowskiEngine
  DEPRECATION: MinkowskiEngine is being installed using the legacy 'setup.py install' method, because the '--no-binary' option was enabled for it and this currently disables local wheel building for projects that don't have a 'pyproject.toml' file. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/11451
  Running command Running setup.py install for MinkowskiEngine
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.7'
  WARNING: Skipping MinkowskiEngine as it is not installed.
  --------------------------------
  | FORCE_CUDA set                |
  --------------------------------
  --------------------------------
  | CUDA compilation set         |
  --------------------------------

  Using BLAS=openblas
  Using the default compiler
  running install
  /home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-39
  creating build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiNonlinearity.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiPooling.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiNormalization.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/sparse_matrix_functions.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiBroadcast.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiCoordinateManager.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/diagnostics.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiNetwork.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiFunctional.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiInterpolation.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/__init__.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiUnion.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiSparseTensor.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiKernelGenerator.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiPruning.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiTensorField.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiTensor.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiChannelwiseConvolution.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiCommon.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiConvolution.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  copying ./MinkowskiEngine/MinkowskiOps.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine
  creating build/lib.linux-x86_64-cpython-39/MinkowskiEngine/utils
  copying ./MinkowskiEngine/utils/coords.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine/utils
  copying ./MinkowskiEngine/utils/summary.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine/utils
  copying ./MinkowskiEngine/utils/__init__.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine/utils
  copying ./MinkowskiEngine/utils/gradcheck.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine/utils
  copying ./MinkowskiEngine/utils/init.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine/utils
  copying ./MinkowskiEngine/utils/quantization.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine/utils
  copying ./MinkowskiEngine/utils/collation.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine/utils
  creating build/lib.linux-x86_64-cpython-39/MinkowskiEngine/modules
  copying ./MinkowskiEngine/modules/resnet_block.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine/modules
  copying ./MinkowskiEngine/modules/senet_block.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine/modules
  copying ./MinkowskiEngine/modules/__init__.py -> build/lib.linux-x86_64-cpython-39/MinkowskiEngine/modules
  running build_ext
  building 'MinkowskiEngineBackend._C' extension
  creating /tmp/pip-req-build-evizr7he/build/temp.linux-x86_64-cpython-39
  creating /tmp/pip-req-build-evizr7he/build/temp.linux-x86_64-cpython-39/tmp
  creating /tmp/pip-req-build-evizr7he/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-evizr7he
  creating /tmp/pip-req-build-evizr7he/build/temp.linux-x86_64-cpython-39/tmp/pip-req-build-evizr7he/src
  creating /tmp/pip-req-build-evizr7he/build/temp.linux-x86_64-cpython-39/pybind
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/tmp/pip-req-build-evizr7he/setup.py", line 320, in <module>
      setup(
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
      super().run_command(command)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
      return orig.install.run(self)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 698, in run
      self.run_command('build')
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
      super().run_command(command)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
      self.run_command(cmd_name)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
      super().run_command(command)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
      self.build_extensions()
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
      build_ext.build_extensions(self)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
      self._build_extensions_serial()
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
      self.build_extension(ext)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
      objects = self.compiler.compile(
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 525, in unix_wrap_ninja_compile
      cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 424, in unix_cuda_flags
      cflags + _get_cuda_arch_flags(cflags))
    File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1562, in _get_cuda_arch_flags
      arch_list[-1] += '+PTX'
  IndexError: list index out of range
  error: subprocess-exited-with-error
  
  × Running setup.py install for MinkowskiEngine did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/jerry/anaconda3/envs/openmmlab/bin/python -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/tmp/pip-req-build-evizr7he/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record /tmp/pip-record-cq605vit/install-record.txt --single-version-externally-managed --compile --install-headers /home/jerry/anaconda3/envs/openmmlab/include/python3.9/MinkowskiEngine --blas=openblas --force_cuda
  cwd: /tmp/pip-req-build-evizr7he/
  Running setup.py install for MinkowskiEngine ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> MinkowskiEngine

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

I would really appreciate if you can take a look again.

Thank you

**Comment by filaPro** [comment]
Please specify smth like this (according to your GPU model) `TORCH_CUDA_ARCH_LIST="6.1 7.0 8.6" before MinkowskiEngine installation command.

**Comment by jerry3chen** [comment]
@filaPro Thank you for the help. I realized that old pytorch does not work for me(cuda not available) so I had to use newer pytorch.
After I re-installed everything(other than pytorch) according to the docker file, I got the following error when running "tools/create_data.py":

```
Traceback (most recent call last):
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/jerry/3D/3d_seg/td3d/td3d/tools/create_data.py", line 6, in <module>
    from tools.data_converter import kitti_converter as kitti
  File "/home/jerry/3D/3d_seg/td3d/td3d/tools/data_converter/kitti_converter.py", line 9, in <module>
    from mmdet3d.core.bbox import box_np_ops, points_cam2img
  File "/home/jerry/3D/3d_seg/td3d/td3d/mmdet3d/core/__init__.py", line 2, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/jerry/3D/3d_seg/td3d/td3d/mmdet3d/core/anchor/__init__.py", line 2, in <module>
    from mmdet.core.anchor import build_prior_generator
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/mmdet/core/bbox/samplers/__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/jerry/anaconda3/envs/openmmlab/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/jerry/anaconda3/envs/openmmlab/lib/python3.9/site-packages/mmcv/_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops7resize_4callERKNS_6TensorEN3c108ArrayRefIlEENS5_8optionalINS5_12MemoryFormatEEE

```
Appreciate your help, thanks

**Comment by filaPro** [comment]
Looks like your mmcv installation is wrong. Did you specify correct versions of pytroch and cuda in this command `mmcv-full==1.6.0 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10.0/index.html`?

**Comment by jerry3chen** [comment]
Thank you @filaPro , we were able to get the program running.

**Comment by kellieda** [comment]
Hello, I also have the same problem. The installed version is indeed mmcvfull == 1.6.0, mmdet == 2.24.1, but still appears "MMCV == 1.6.0 is used but incompatible. Please install mmcv > = 2.0.0 rc4, < 2.1.0.", do you have any good solutions? Thanks
