### ISSUE TITLE
Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by xiongcs** [SamsungLabs/td3d#22]
When I was running "`python tools/train.pyconfigs/td3d _ is/td3d _ is _ s3dis-3d-13class _ pretrain.py`"in docker, the following error appeared.
```
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 259, in main
    meta=meta)
  File "/mmdetection3d/mmdet3d/apis/train.py", line 351, in train_model
    meta=meta)
  File "/mmdetection3d/mmdet3d/apis/train.py", line 319, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/mmdet/datasets/dataset_wrappers.py", line 178, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 308, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 435, in __getitem__
    data = self.prepare_train_data(idx)
  File "/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 225, in prepare_train_data
    input_dict = self.get_data_info(index)
  File "/mmdetection3d/mmdet3d/datasets/s3dis_dataset.py", line 128, in get_data_info
    info = self.data_infos[index]
KeyError: 0
```

**Comment by oneformer3d-contributor** [comment]
Have you preprocessed s3dis data with this repo and not we the official mmdetection3d codebase?

**Comment by filaPro** [comment]
Have you preprocessed s3dis data with this repo and not we the official mmdetection3d codebase?

**Comment by xiongcs** [comment]
> Have you preprocessed s3dis data with this repo and not we the official mmdetection3d codebase?您是否使用此存储库预处理了 s3dis 数据，而不是我们官方的 mmdetection3d 代码库？

I preprocessed the s3dis data, and I used the docker image pulled by your dockerfile to run the project, which should be your official codebase.This is my s3dis folder.
![Uploading 3.png…]()

**Comment by xiongcs** [comment]
![3](https://github.com/SamsungLabs/td3d/assets/151824485/350810c3-c8b6-405f-af69-8ad9c0b24244)
